substitutions:
  run_uom: s
  run_duration_initial_value: '5'
  rain_sensor_id: rain_sensor
  rtc_id: rtc_time
  timezone: CST
  day_update_interval: 3min
  hourly_update_interval: 60min
  default_update_interval: 30s

esphome:
  name: waveshare-esprinkler
  comment: "WaveShare ESP32-S3-POE-ETH-8DI-8RO device"
  friendly_name: "Waveshare Esprinkler"
  name_add_mac_suffix: false
  on_boot:
    then:
      - pcf85063.read_time
      - rtttl.play:
          rtttl: scale_up:d=32,o=5,b=150:c,e,8g
      - light.turn_on:
          id: rgb_led
          brightness: 100%
          red: 5%
          green: 100%
          blue: 5%

esp32:
  board: esp32s3box #esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: arduino

psram:
  mode: octal
  speed: 80MHz

# Enable Home Assistant API
api:
  encryption:
    key: "thz0x33OT4pfVlgULREJgurUDENy41juibsZyTVdo+0="
  actions:
    # Ability to command the buzzer from Home Assistant
    - action: rtttl_play
      variables:
        song_str: string
      then:
        - rtttl.play:
            rtttl: !lambda 'return song_str;'

ota:
  - platform: esphome
    password: "f063f4abfffbdd18a9dcf4d5e21d8610"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Waveshare-Esprinkler"
    password: "h0JC2RoXPde1"

web_server:
  version: 3

packages:
  # Time, IP, MAC addr, Wifi info, Temperature, etc
  - !include hardware/waveshare-8DI-8RO-C.yaml
  - !include sensors/generic_sensors.yaml
  
  # - !include controller/controller.yaml
  # - !include controller/controller_status.yaml
  # - !include schedule/schedule.yaml
  
  ##### Uncomment below if compiling from esphome builder #####
  # - !include esprinkler/sensors/generic_sensors.yaml
  # - !include esprinkler/controller/controller.yaml
  # - !include esprinkler/controller/controller_status.yaml
  # - !include esprinkler/schedule/schedule.yaml

# Enable logging
logger:

debug:
  update_interval: 5s

sprinkler:
  - id: main_lawn_ctrlr
    main_switch: "Start Cycle"
    auto_advance_switch: "Auto Advance"
    multiplier_number: "Run Duration Multiplier"
    repeat_number: "Repeat Cycle"
    # VERIFY THIS IS SUFFICENT
    valve_open_delay: 5s
    standby_switch: "Disable All Zones"
    valves:
      - valve_switch: "Zone 1"
        enable_switch: "Enable Zone 1"
        run_duration_number: 
          id: z1_run_duration_number
          name: "Zone 1 Run Duration"
          initial_value: 30
          unit_of_measurement: ${run_uom}
        valve_switch_id: relay1

      - valve_switch: "Zone 2"
        enable_switch: "Enable Zone 2"
        run_duration_number: 
          id: z2_run_duration_number
          name: "Zone 2 Run Duration"
          initial_value: 30
          unit_of_measurement: ${run_uom}
        valve_switch_id: relay2

      - valve_switch: "Zone 3"
        enable_switch: "Enable Zone 3"
        run_duration_number: 
          id: z3_run_duration_number
          name: "Zone 3 Run Duration"
          initial_value: 30
          unit_of_measurement: ${run_uom}
        valve_switch_id: relay3

      - valve_switch: "Zone 4"
        enable_switch: "Enable Zone 4"
        run_duration_number: 
          id: z4_run_duration_number
          name: "Zone 4 Run Duration"
          initial_value: 30
          unit_of_measurement: ${run_uom}
        valve_switch_id: relay4
      
      - valve_switch: "Zone 5"
        enable_switch: "Enable Zone 5"
        run_duration_number: 
          id: z5_run_duration_number
          name: "Zone 5 Run Duration"
          initial_value: 30
          unit_of_measurement: ${run_uom}
        valve_switch_id: relay5

      - valve_switch: "Zone 6"
        enable_switch: "Enable Zone 6"
        run_duration_number: 
          id: z6_run_duration_number
          name: "Zone 6 Run Duration"
          initial_value: 30
          unit_of_measurement: ${run_uom}
        valve_switch_id: relay6

      - valve_switch: "Zone 7"
        enable_switch: "Enable Zone 7"
        run_duration_number: 
          id: z7_run_duration_number
          name: "Zone 7 Run Duration"
          initial_value: 30
          unit_of_measurement: ${run_uom}
        valve_switch_id: relay7

      - valve_switch: "Zone 8"
        enable_switch: "Enable Zone 8"
        run_duration_number: 
          id: z8_run_duration_number
          name: "Zone 8 Run Duration"
          initial_value: 30
          unit_of_measurement: ${run_uom}
        valve_switch_id: relay8