substitutions:
  sched_a_name: "Sched A"

mapping:
  - id: string_map
    from: int
    to: string
    entries:
      0: Sunday
      1: Monday
      2: Tuesday
      3: Wednesday
      4: Thursday
      5: Friday
      6: Saturday

packages:
  # 
  days_sw: !include 
    file: days_sw.yaml
    vars:
      sched_id: a
      sched_name: ${sched_a_name}
  zone_duration: !include 
    file: zone_duration.yaml
    vars:
      sched_id: a
      sched_name: ${sched_a_name}
  # zone_enable_sw: !include zone_enable_sw.yaml
  sched_a: !include
    file: zone_enable_sw.yaml
    vars:
      sched_id: a
      sched_name: ${sched_a_name}
  run_script: !include
    file: run_script.yaml
    vars:
      sched_id: a
      sched_name: ${sched_a_name}
  run_options: !include
    file: run_options.yaml
    vars:
      sched_id: a
      sched_name: ${sched_a_name}


globals:
  # Schedule A
  - id: glob_sched_a
    type: bool[7]
    initial_value: '{false,false,false,false,false,false,false}'
    restore_value: true

  #   # Schedule B
  # - id: glob_sched_b
  #   type: bool[7]
  #   initial_value: '{false,false,false,false,false,false,false}'
  #   restore_value: true

datetime:
  # Schedule A Time
  - platform: template
    id: start_time
    type: time
    name: Start Time
    optimistic: yes
    initial_value: "02:00"
    restore_value: true

  # Schedule B Time
  # - platform: template
  #   id: start_time_b
  #   type: time
  #   name: Start Time B
  #   optimistic: yes
  #   initial_value: "02:00"
  #   restore_value: true


interval:
  - interval: 30s
    then:
      - lambda: |-
          int cur_day = id(ha_time).now().day_of_week-1;
          int cur_hr = id(ha_time).now().hour;
          int cur_min = id(ha_time).now().minute;
          int sched_hr = id(start_time).hour;
          int sched_min = id(start_time).minute;

          if ( id(cntrlr_bypass).state ) {
            // if ( id(rain_check).state ) {

            // }
            // id(scheduler).publish_state("Bypass")
            return;
          }

          if ( id(sprinkler_cntrlr_main_switch_id).state ) {
            id(scheduler).publish_state("Running");
            return;
          }

          if ( (id(glob_sched_a)[cur_day] & (cur_hr < id(start_time).hour)) || ((cur_hr == id(start_time).hour) & (cur_min < id(start_time).minute)) ){
            id(scheduler).publish_state("Next Run: Schedule A - " + id(string_map)[cur_day] + " @" + id(start_time).state_as_esptime().strftime("%I:%M %p"));
            return;
          }

          // Check next run time after today

          else {
            id(scheduler).publish_state("ELSE: >>" + id(start_time).state_as_esptime().strftime("%H:%M:%S"));//buffer, sizeof(buffer), "%H:%M:%S"));
          }

  - interval: 30s
    then:
      - lambda: |-
          // Check if Schedule A is running today
          // if (id(rain_check).state){
          //   if (id(sprinkler_cntrlr_main_switch_id).state) {
          //     id(cntrlr_bypass).publish_state(true);
          //     id(cntrlr_bypass).turn_on();
          //     id(${cntrlr_id}).clear_queued_valves();
          //   }
          //   return;
          // }
          if (id(glob_sched_a)[id(ha_time).now().day_of_week-1]){
            if (id(sprinkler_cntrlr).paused_valve().has_value()){
              ESP_LOGI("main", ">>>>>>>>>Cycle skipped due to system PAUSED");
              return;
            }

            int current_hour = id(ha_time).now().hour;
            int current_minute = id(ha_time).now().minute;
            int desired_hour = id(start_time).hour;
            int desired_minute = id(start_time).minute;
            // Check if it is the desired hour and the automation should run
            if (current_hour == desired_hour && current_minute == desired_minute) {
              if (id(cntrlr_bypass).state & id(rain_check).state){
                id(scheduler).publish_state("[INFO] Schedule A skipped for Rain Bypass");
              }
              id(run_schedule_a).execute();
              ESP_LOGI("main", "Cycle started...");
            }
          }

switch:
  # Switch templates for days to water
  # TODO
  #   - Add schedule B&C
  - platform: template
    id: a_schedule_sw
    name: "Schedule A"
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - script.execute: run_schedule_a
    turn_off_action: 
      - lambda: id(a_schedule_sw).publish_state(false);
      - sprinkler.shutdown: ${cntrlr_id}

